name: Deploy Pygame to Web

on:
  push:
    branches: [ "main" ] # Hoặc "master" tùy thuộc vào tên nhánh chính của bạn

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pygame-script (pygbag)
        run: |
          python -m pip install --upgrade pip
          pip install pygbag

      - name: Build Web Version
        run: |
          # Build game sử dụng pygbag dưới dạng template tiêu chuẩn
          python -m pygbag --build $GITHUB_WORKSPACE/main.py

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
